window.AMUNRA_STORAGE = {
  products: "amunraProducts",
  slides: "amunraHeroSlides",
  site: "amunraSiteContent",
};

const amunraProductImages = {
  phoneA: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80",
  phoneB: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80",
  phoneC: "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=600&q=80",
  tablet: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=600&q=80",
  laptop: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80",
  watch: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
  audio: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
  charger: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80",
};

window.AMUNRA_DEFAULTS = {
  site: {
    brandName: "Amunra",
    brandSubtitle: "Mobile Store",
    topMessage: "Cam kết máy chính hãng, bảo hành rõ ràng",
    hotline: "0967.29.29.29",
    hotlineTel: "0967292929",
    email: "hello@amunra.vn",
    address: "29 Đường Amunra, TP.HCM",
    footerIntro:
      "Amunra là mẫu giao diện thương mại điện tử cho cửa hàng công nghệ, tối ưu cho khuyến mãi, tìm kiếm sản phẩm và chuyển đổi nhanh.",
    promoOneLabel: "Thu cũ đổi mới",
    promoOneTitle: "Lên đời tiết kiệm tới 6 triệu",
    promoTwoLabel: "Bảo hành Amunra Care",
    promoTwoTitle: "Đổi máy nhanh, hỗ trợ tận nơi",
    tradeEyebrow: "Amunra Upgrade",
    tradeTitle: "Thu cũ đổi mới, định giá minh bạch",
    tradeDescription:
      "Mang máy cũ đến Amunra để được kiểm tra miễn phí, bù tiền lên đời máy mới và chuyển dữ liệu tại chỗ.",
  },
  heroSlides: [
    {
      eyebrow: "Amunra Mega Sale",
      title: "Điện thoại flagship giảm đến 35%",
      description: "Ưu đãi trả góp 0%, thu cũ đổi mới và giao nhanh trong ngày tại TP.HCM.",
      buttonText: "Xem giá sốc",
      buttonHref: "#deals",
      image: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=1400&q=80",
      alt: "Kệ sản phẩm công nghệ tại Amunra",
    },
    {
      eyebrow: "Back to Work",
      title: "Laptop mỏng nhẹ, tablet học tập",
      description: "Combo thiết bị cho văn phòng, sáng tạo nội dung và học tập online.",
      buttonText: "Chọn thiết bị",
      buttonHref: "#computers",
      image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=80",
      alt: "Laptop và thiết bị làm việc hiện đại",
    },
    {
      eyebrow: "Phụ kiện thông minh",
      title: "Tai nghe, sạc nhanh, đồng hồ",
      description: "Giảm sâu khi mua kèm điện thoại, bảo hành 1 đổi 1 trong 30 ngày.",
      buttonText: "Mua phụ kiện",
      buttonHref: "#accessories",
      image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1400&q=80",
      alt: "Tai nghe công nghệ",
    },
  ],
  products: [
    {
      name: "Amunra Nova X Pro 256GB",
      type: "phone",
      section: "flash",
      image: amunraProductImages.phoneA,
      specs: ["AMOLED 120Hz", "Camera 108MP"],
      price: 18990000,
      oldPrice: 22990000,
      badges: ["Hot", "Trả góp 0%"],
      stock: 62,
    },
    {
      name: "Amunra Fold One 512GB",
      type: "phone",
      section: "flash",
      image: amunraProductImages.phoneB,
      specs: ["Gập mỏng", "Pin 5000mAh"],
      price: 31990000,
      oldPrice: 39990000,
      badges: ["Siêu giảm giá"],
      stock: 42,
    },
    {
      name: "Galaxy S Amunra Edition 12GB 256GB",
      type: "phone",
      section: "flash",
      image: amunraProductImages.phoneC,
      specs: ["AI Camera", "Sạc nhanh"],
      price: 22990000,
      oldPrice: 28990000,
      badges: ["Chính hãng"],
      stock: 55,
    },
    {
      name: "Amunra Pad Air 11 inch 128GB",
      type: "tablet",
      section: "flash",
      image: amunraProductImages.tablet,
      specs: ["Màn 2.8K", "Wi-Fi 6"],
      price: 8990000,
      oldPrice: 11990000,
      badges: ["Trả góp 0%"],
      stock: 38,
    },
    {
      name: "Amunra Watch S9 LTE 45mm",
      type: "accessory",
      section: "flash",
      image: amunraProductImages.watch,
      specs: ["eSIM", "Chống nước"],
      price: 4990000,
      oldPrice: 6990000,
      badges: ["Hot"],
      stock: 70,
    },
    {
      name: "Amunra Buds Pro ANC",
      type: "accessory",
      section: "flash",
      image: amunraProductImages.audio,
      specs: ["ANC", "Pin 32 giờ"],
      price: 2190000,
      oldPrice: 3490000,
      badges: ["Mua kèm giảm"],
      stock: 48,
    },
    {
      name: "Amunra Neo 5G 8GB 256GB",
      type: "phone",
      section: "phones",
      image: amunraProductImages.phoneB,
      specs: ["5G", "OIS 64MP"],
      price: 7990000,
      oldPrice: 9990000,
      badges: ["Bán chạy"],
      stock: 83,
    },
    {
      name: "Amunra Max 5G 12GB 512GB",
      type: "phone",
      section: "phones",
      image: amunraProductImages.phoneA,
      specs: ["Snapdragon", "144Hz"],
      price: 14990000,
      oldPrice: 18990000,
      badges: ["Hot"],
      stock: 58,
    },
    {
      name: "iPhone Like New Amunra Care 128GB",
      type: "phone",
      section: "phones",
      image: amunraProductImages.phoneC,
      specs: ["Like new", "BH 12 tháng"],
      price: 11990000,
      oldPrice: 13990000,
      badges: ["Kho máy cũ"],
      stock: 35,
    },
    {
      name: "Amunra Pad Mini 8.7 inch LTE",
      type: "tablet",
      section: "computers",
      image: amunraProductImages.tablet,
      specs: ["LTE", "Pin 8000mAh"],
      price: 5490000,
      oldPrice: 6990000,
      badges: ["Sinh viên"],
      stock: 67,
    },
    {
      name: "AmunraBook Air 13 inch M-Series",
      type: "tablet",
      section: "computers",
      image: amunraProductImages.laptop,
      specs: ["16GB RAM", "512GB SSD"],
      price: 24990000,
      oldPrice: 28990000,
      badges: ["Văn phòng"],
      stock: 40,
    },
    {
      name: "AmunraBook Pro 14 inch Creator",
      type: "tablet",
      section: "computers",
      image: amunraProductImages.laptop,
      specs: ["Màn 3K", "Pin 18 giờ"],
      price: 32990000,
      oldPrice: 36990000,
      badges: ["Đồ họa"],
      stock: 25,
    },
    {
      name: "Amunra Charge GaN 65W",
      type: "accessory",
      section: "accessories",
      image: amunraProductImages.charger,
      specs: ["GaN", "3 cổng"],
      price: 690000,
      oldPrice: 990000,
      badges: ["Mua kèm"],
      stock: 76,
    },
    {
      name: "Amunra Case Shield MagSafe",
      type: "accessory",
      section: "accessories",
      image: amunraProductImages.phoneA,
      specs: ["Chống sốc", "MagSafe"],
      price: 390000,
      oldPrice: 590000,
      badges: ["Phụ kiện"],
      stock: 88,
    },
    {
      name: "Amunra Power Bank 20.000mAh",
      type: "accessory",
      section: "accessories",
      image: amunraProductImages.charger,
      specs: ["PD 30W", "LED"],
      price: 890000,
      oldPrice: 1290000,
      badges: ["Bán chạy"],
      stock: 63,
    },
  ],
};
