window.AMUNRA_STORAGE = {
  products: "amunraProducts",
  slides: "amunraHeroSlides",
  site: "amunraSiteContent",
};

const tgddSearch = (keyword) => `https://www.thegioididong.com/tim-kiem?key=${encodeURIComponent(keyword)}`;

const amunraProductImages = {
  iphone: "https://images.unsplash.com/photo-1695048133142-1a20484d2569?auto=format&fit=crop&w=600&q=80",
  samsung: "https://images.unsplash.com/photo-1610945415295-d9bbf067e59c?auto=format&fit=crop&w=600&q=80",
  xiaomi: "https://images.unsplash.com/photo-1511707171634-5f897ff02aa9?auto=format&fit=crop&w=600&q=80",
  oppo: "https://images.unsplash.com/photo-1598327105666-5b89351aff97?auto=format&fit=crop&w=600&q=80",
  vivo: "https://images.unsplash.com/photo-1565849904461-04a58ad377e0?auto=format&fit=crop&w=600&q=80",
  laptop: "https://images.unsplash.com/photo-1517336714731-489689fd1ca8?auto=format&fit=crop&w=600&q=80",
  tablet: "https://images.unsplash.com/photo-1544244015-0df4b3ffc6b0?auto=format&fit=crop&w=600&q=80",
  watch: "https://images.unsplash.com/photo-1523275335684-37898b6baf30?auto=format&fit=crop&w=600&q=80",
  audio: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=600&q=80",
  charger: "https://images.unsplash.com/photo-1583863788434-e58a36330cf0?auto=format&fit=crop&w=600&q=80",
};

window.AMUNRA_DEFAULTS = {
  site: {
    brandName: "Amunra",
    brandSubtitle: "Mobile Store",
    topMessage: "Tổng hợp sản phẩm công nghệ tham khảo từ Thế Giới Di Động",
    hotline: "0967.29.29.29",
    hotlineTel: "0967292929",
    email: "hello@amunra.vn",
    address: "29 Đường Amunra, TP.HCM",
    footerIntro:
      "Amunra là website giới thiệu và điều hướng sản phẩm công nghệ. Giá, khuyến mãi và tồn kho cần được kiểm tra lại tại Thế Giới Di Động trước khi mua.",
    promoOneLabel: "Nguồn sản phẩm",
    promoOneTitle: "Tham khảo từ thegioididong.com",
    promoTwoLabel: "Lưu ý giá bán",
    promoTwoTitle: "Giá hiển thị chỉ là tham khảo",
    tradeEyebrow: "Amunra Affiliate",
    tradeTitle: "Khám phá sản phẩm công nghệ từ Thế Giới Di Động",
    tradeDescription:
      "Chọn sản phẩm bạn quan tâm, xem thông tin nổi bật và truy cập nguồn Thegioididong để kiểm tra giá, khuyến mãi, tồn kho mới nhất.",
  },
  heroSlides: [
    {
      eyebrow: "Amunra x TGDD",
      title: "Tổng hợp điện thoại nổi bật từ Thế Giới Di Động",
      description: "Danh sách sản phẩm công nghệ được gom theo nhóm để người dùng dễ tìm, so sánh và đi tới trang nguồn.",
      buttonText: "Xem sản phẩm",
      buttonHref: "#phones",
      image: "https://images.unsplash.com/photo-1550009158-9ebf69173e03?auto=format&fit=crop&w=1400&q=80",
      alt: "Sản phẩm công nghệ và điện thoại",
    },
    {
      eyebrow: "Laptop & Tablet",
      title: "Thiết bị học tập, làm việc và sáng tạo",
      description: "Gợi ý laptop, tablet và thiết bị thông minh đang được nhiều người dùng quan tâm.",
      buttonText: "Xem thiết bị",
      buttonHref: "#computers",
      image: "https://images.unsplash.com/photo-1516321318423-f06f85e504b3?auto=format&fit=crop&w=1400&q=80",
      alt: "Laptop và tablet",
    },
    {
      eyebrow: "Phụ kiện",
      title: "Tai nghe, đồng hồ, sạc nhanh và phụ kiện",
      description: "Bổ sung phụ kiện phù hợp để tăng giá trị đơn hàng và tối ưu chuyển đổi affiliate.",
      buttonText: "Xem phụ kiện",
      buttonHref: "#accessories",
      image: "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?auto=format&fit=crop&w=1400&q=80",
      alt: "Phụ kiện công nghệ",
    },
  ],
  products: [
    {
      name: "iPhone 16 Pro Max",
      type: "phone",
      section: "flash",
      image: amunraProductImages.iphone,
      specs: ["Apple A18 Pro", "Màn hình Super Retina XDR", "Camera Pro"],
      price: 30990000,
      oldPrice: 34990000,
      badges: ["TGDD", "Apple", "Nổi bật"],
      stock: 72,
      sourceUrl: tgddSearch("iPhone 16 Pro Max"),
    },
    {
      name: "Samsung Galaxy S25 Ultra",
      type: "phone",
      section: "flash",
      image: amunraProductImages.samsung,
      specs: ["Galaxy AI", "Camera 200MP", "S Pen"],
      price: 28990000,
      oldPrice: 33990000,
      badges: ["TGDD", "Samsung", "Flagship"],
      stock: 65,
      sourceUrl: tgddSearch("Samsung Galaxy S25 Ultra"),
    },
    {
      name: "Xiaomi Redmi Note 14 Pro 5G",
      type: "phone",
      section: "flash",
      image: amunraProductImages.xiaomi,
      specs: ["5G", "AMOLED 120Hz", "Camera 200MP"],
      price: 8490000,
      oldPrice: 9990000,
      badges: ["TGDD", "Xiaomi", "Tầm trung"],
      stock: 80,
      sourceUrl: tgddSearch("Xiaomi Redmi Note 14 Pro 5G"),
    },
    {
      name: "OPPO Reno14",
      type: "phone",
      section: "flash",
      image: amunraProductImages.oppo,
      specs: ["Camera chân dung", "Sạc nhanh", "Thiết kế mỏng"],
      price: 12990000,
      oldPrice: 14990000,
      badges: ["TGDD", "OPPO"],
      stock: 58,
      sourceUrl: tgddSearch("OPPO Reno14"),
    },
    {
      name: "iPhone 16",
      type: "phone",
      section: "phones",
      image: amunraProductImages.iphone,
      specs: ["Apple A18", "Camera Fusion", "iOS"],
      price: 20990000,
      oldPrice: 22990000,
      badges: ["TGDD", "Apple"],
      stock: 75,
      sourceUrl: tgddSearch("iPhone 16"),
    },
    {
      name: "Samsung Galaxy A56 5G",
      type: "phone",
      section: "phones",
      image: amunraProductImages.samsung,
      specs: ["5G", "Super AMOLED", "Pin dùng cả ngày"],
      price: 9490000,
      oldPrice: 10990000,
      badges: ["TGDD", "Samsung", "Bán chạy"],
      stock: 84,
      sourceUrl: tgddSearch("Samsung Galaxy A56 5G"),
    },
    {
      name: "vivo V50",
      type: "phone",
      section: "phones",
      image: amunraProductImages.vivo,
      specs: ["Camera chân dung", "Màn hình AMOLED", "Sạc nhanh"],
      price: 11990000,
      oldPrice: 13990000,
      badges: ["TGDD", "vivo"],
      stock: 54,
      sourceUrl: tgddSearch("vivo V50"),
    },
    {
      name: "realme 14 Pro",
      type: "phone",
      section: "phones",
      image: amunraProductImages.xiaomi,
      specs: ["AMOLED", "Pin lớn", "Hiệu năng tốt"],
      price: 8990000,
      oldPrice: 10490000,
      badges: ["TGDD", "realme"],
      stock: 60,
      sourceUrl: tgddSearch("realme 14 Pro"),
    },
    {
      name: "MacBook Air M4 13 inch",
      type: "tablet",
      section: "computers",
      image: amunraProductImages.laptop,
      specs: ["Apple M4", "Mỏng nhẹ", "Pin lâu"],
      price: 26990000,
      oldPrice: 29990000,
      badges: ["TGDD", "MacBook"],
      stock: 40,
      sourceUrl: tgddSearch("MacBook Air M4 13 inch"),
    },
    {
      name: "iPad Air M3",
      type: "tablet",
      section: "computers",
      image: amunraProductImages.tablet,
      specs: ["Chip M3", "Màn Liquid Retina", "Hỗ trợ Apple Pencil"],
      price: 16990000,
      oldPrice: 18990000,
      badges: ["TGDD", "iPad"],
      stock: 52,
      sourceUrl: tgddSearch("iPad Air M3"),
    },
    {
      name: "Samsung Galaxy Tab S10 FE",
      type: "tablet",
      section: "computers",
      image: amunraProductImages.tablet,
      specs: ["S Pen", "Màn hình lớn", "Học tập làm việc"],
      price: 11990000,
      oldPrice: 13990000,
      badges: ["TGDD", "Tablet"],
      stock: 45,
      sourceUrl: tgddSearch("Samsung Galaxy Tab S10 FE"),
    },
    {
      name: "Laptop ASUS Vivobook",
      type: "tablet",
      section: "computers",
      image: amunraProductImages.laptop,
      specs: ["Văn phòng", "Mỏng nhẹ", "SSD"],
      price: 13990000,
      oldPrice: 15990000,
      badges: ["TGDD", "Laptop"],
      stock: 48,
      sourceUrl: tgddSearch("Laptop ASUS Vivobook"),
    },
    {
      name: "Apple Watch Series 10",
      type: "accessory",
      section: "accessories",
      image: amunraProductImages.watch,
      specs: ["Theo dõi sức khỏe", "Màn hình Always-On", "watchOS"],
      price: 9990000,
      oldPrice: 11990000,
      badges: ["TGDD", "Apple Watch"],
      stock: 70,
      sourceUrl: tgddSearch("Apple Watch Series 10"),
    },
    {
      name: "AirPods Pro 2",
      type: "accessory",
      section: "accessories",
      image: amunraProductImages.audio,
      specs: ["Chống ồn chủ động", "Spatial Audio", "USB-C"],
      price: 5490000,
      oldPrice: 6490000,
      badges: ["TGDD", "Tai nghe"],
      stock: 74,
      sourceUrl: tgddSearch("AirPods Pro 2"),
    },
    {
      name: "Sạc nhanh Anker 65W",
      type: "accessory",
      section: "accessories",
      image: amunraProductImages.charger,
      specs: ["GaN", "USB-C", "Sạc nhanh"],
      price: 790000,
      oldPrice: 990000,
      badges: ["TGDD", "Phụ kiện"],
      stock: 86,
      sourceUrl: tgddSearch("Sạc nhanh Anker 65W"),
    },
    {
      name: "Pin sạc dự phòng 20.000mAh",
      type: "accessory",
      section: "accessories",
      image: amunraProductImages.charger,
      specs: ["Dung lượng lớn", "USB-C", "Du lịch"],
      price: 690000,
      oldPrice: 890000,
      badges: ["TGDD", "Power bank"],
      stock: 78,
      sourceUrl: tgddSearch("Pin sạc dự phòng 20000mAh"),
    },
  ],
};
